name: Fetch Project Column ID

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  fetch-and-filter-project-details:
    runs-on: ubuntu-latest

    env:
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
      PROJECT_NUMBER: 14
      VIEW_NUMBER: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch project data and filter for Inbox column ID
        run: |
          echo "{\"query\":\"query { user(login: \"costateixeira\") { projectV2(number: 14) { id, title, view(number: 1) { id, name, fields(first: 5) { nodes { ... on ProjectV2SingleSelectField { name, options { id, name } } } } } } } }\"}"\

          DATA=$(curl -v --request POST \
            --url https://api.github.com/graphql \
            --header "Authorization: Bearer $GITHUB_TOKEN" \
            --header "Content-Type: application/json" \
            --data "{\"query\":\"query { user(login: \\\"costateixeira\\\") { projectV2(number: 14) { id, title, view(number: 1) { id, name, fields(first: 5) { nodes { ... on ProjectV2SingleSelectField { name, options { id, name } } } } } } } }\"}" \
            --silent -v
          
          echo "Fetched Data:"
          echo "$DATA" 
          
          echo "Fetched Data:"
          echo "$DATA" | jq
          
          if [[ $(echo "$DATA" | jq -r '.data.user.projectV2') != "null" ]]; then
              COLUMN_ID=$(echo "$DATA" | jq -r '.data.user.projectV2.view.fields.nodes[] | select(.options[].name == "Inbox").options[] | select(.name == "Inbox") | .id')
              PROJECT_ID=$(echo "$DATA" | jq -r '.data.user.projectV2.id')
              echo "Project ID: $PROJECT_ID"
              echo "Inbox Column ID: $COLUMN_ID"
          else
              echo "Error: Could not resolve to a ProjectV2 with the number 14."
              echo $(echo "$DATA" | jq -r '.errors[].message')
          fi
          

          

      - name: Install jq
        run: sudo apt install -y jq
